# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geo-Ellipsoid
version:      0.902
version_from: lib/Geo/Ellipsoid.pm
installdirs:  site
requires:
    Test::Number::Delta:           0.16
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
